// Mocks generated by Mockito 5.4.4 from annotations
// in common/test/features/rate_us/presentation/cubit/rate_us_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:common/features/rate_us/data/models/rate_us_request.dart'
    as _i8;
import 'package:common/features/rate_us/data/models/rate_us_response.dart'
    as _i7;
import 'package:common/features/rate_us/data/models/update_rate_us_request.dart'
    as _i10;
import 'package:common/features/rate_us/data/models/update_rate_us_response.dart'
    as _i9;
import 'package:common/features/rate_us/domain/repositories/rate_us_repository.dart'
    as _i2;
import 'package:common/features/rate_us/domain/usecases/rate_us_usecase.dart'
    as _i4;
import 'package:core/config/error/failure.dart' as _i6;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRateUsRepository_0 extends _i1.SmartFake
    implements _i2.RateUsRepository {
  _FakeRateUsRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RateUsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRateUsUseCase extends _i1.Mock implements _i4.RateUsUseCase {
  MockRateUsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RateUsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeRateUsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.RateUsRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.RateUsResponse>> call(
          _i8.RateUsRequest? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.RateUsResponse>>.value(
                _FakeEither_1<_i6.Failure, _i7.RateUsResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.RateUsResponse>>);

  @override
  _i5.Future<
      _i3.Either<_i6.Failure, _i9.UpdateRateUsResponse>> updateRateUsRecord(
          _i10.UpdateRateUsRequest? rateUsRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRateUsRecord,
          [rateUsRequest],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i9.UpdateRateUsResponse>>.value(
                _FakeEither_1<_i6.Failure, _i9.UpdateRateUsResponse>(
          this,
          Invocation.method(
            #updateRateUsRecord,
            [rateUsRequest],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i9.UpdateRateUsResponse>>);
}
