name: mmfsl
repository: https://bitbucket.org/one-customer-app/mobile

packages:
  - '**'

scripts:

  dart-analyze:
    description: "run dart analyzer"
    run: melos exec dart analyze
  flutter-analyze:
    description: "run flutter analyzer"
    run: melos exec flutter analyze
  merge-trace-files:
    description: Merge all packages coverage trace files ignoring data related to generated files.
    run: >
      coverde rm MELOS_ROOT_PATH/coverage/filtered.lcov.info &&
      melos exec --file-exists=coverage/lcov.info -- "coverde filter --input ./coverage/lcov.info --output MELOS_ROOT_PATH/coverage/filtered.lcov.info --paths-parent MELOS_PACKAGE_PATH --filters '\.g\.dart'"
    packageFilters:
      flutter: true
      dirExists: test
  # run-coverage:
  #   description: Merge all packages coverage trace files ignoring data related to generated files.
  #   run: >
  #     coverde rm MELOS_ROOT_PATH/coverage/filtered.lcov.info  &&
  #     melos exec --file-exists=coverage/lcov.info -- "coverde filter --input ./coverage/lcov.info --output MELOS_ROOT_PATH/coverage/filtered.lcov.info --paths-parent MELOS_PACKAGE_PATH --filters '\.g\.dart'"
  #   packageFilters:
  #     flutter: true
  #     dirExists: test
  checkCoverage:
    run: melos run merge-trace-files && genhtml coverage/filtered.lcov.info -o coverage/html
  clean:
    run: melos exec flutter clean
  getdependencies:
    run: melos exec flutter pub get