name: fintogo
description: "fintogo"

publish_to: "none"

version: 1.0.0+5

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  common:
    path: ./common
  core:
    path: ./core
  auth:
    path: ./features/auth
  locate_us:
    path: features/locate_us
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_image_compress: ^2.2.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  global: ^0.0.28
  go_router: ^13.0.1
  html: ^0.15.4
  image_picker: ^1.0.7
  melos: ^4.1.0
  oktoast: ^3.4.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  skeletonizer: ^1.2.0
  flutter_logs: ^2.1.12
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.2.1+1
dev_dependencies:
  connectivity_plus: ^5.0.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  open_settings_plus: ^0.3.2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/svg/
    - assets/certify/certificateone.pem
    - assets/stubdata/locate_us/
    - assets/stubdata/language.json
    - assets/stubdata/app_labels.json
    - assets/stubdata/send_otp.json
    - assets/stubdata/validate_otp.json
    - assets/stubdata/autheticate.json
    - assets/stubdata/autheticate_ucic.json
    - assets/stubdata/consent.json
    - assets/stubdata/registration_status.json
    - assets/stubdata/register_user.json
    - assets/stubdata/
    - assets/stubdata/foreclosure/
    - assets/stubdata/product_details/
    - assets/stubdata/privacy_policy/
    - assets/stubdata/terms_conditions/
    - assets/stubdata//
    - assets/stubdata/login_response.json
    - assets/stubdata/validate_device.json
    - assets/stubdata/update_theme_detail_response.json
    - assets/stubdata/ach/
    - assets/stubdata/save_device.json
    - assets/stubdata/validate_multiple_device.json
    - assets/stubdata/product_fearure.json
    - assets/stubdata/faq/
    - assets/stubdata/loan_refund/
    - assets/stubdata/update_app_language.json
    - assets/stubdata/applaunch_config_response.json
    - assets/stubdata/loan_cancellation/
    - assets/stubdata/create_mpin.json
    - assets/stubdata/profile/
    - assets/stubdata/rate_us/
    - assets/stubdata/noc/
    - assets/stubdata/landing_page/landing_page_data.json
    - assets/stubdata/landing_page/landing_page_offer_banner.json
    - assets/stubdata/landing_page/loan_amount_response.json
    - assets/stubdata/landing_page/pre_approved_offers.json
    - assets/stubdata/landing_page/pre_approve_offer_response.json
    - assets/stubdata/service_requests/reopen_service_request.json
    - assets/stubdata/service_requests/payment.json
    - assets/stubdata/service_requests/miscellaneous.json
    - assets/stubdata/service_requests/refund.json
    - mobile-config/common/dev.env
    - mobile-config/common/uat.env
    - mobile-config/common/prod.env


  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
    - family: Karla
      fonts:
        - asset: assets/fonts/Karla-Regular.ttf
