name: core
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  app_launch_check:
    path: ../plugins/app_launch_check
  locate_us:
    path: ../features/locate_us
  common:
    path: ../common
  auth:
    path: ../features/auth

  # UI
  flutter_screenutil: ^5.9.0

  # network
  dio: ^5.4.0
  cached_network_image: ^3.3.0
  dartz: ^0.10.1
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.2
  flutter_udid: ^3.0.0
  flutter_jailbreak_detection: ^1.10.0
  go_router: ^13.0.1
  permission_handler: ^11.3.1
  logger: ^2.0.2+1
  get_it: ^7.6.6
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  vpn_connection_detector: ^1.0.6
  flutter_windowmanager: ^0.2.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.5
  flutter_gallery_3d: ^1.1.1
  bloc_test: ^9.1.6
  mockito: ^5.0.0
  build_runner: ^2.4.7
  step_progress_indicator: ^1.0.2
  ymchat_flutter: ^2.13.0


  # Encryption
  encrypt: ^5.0.3
  fast_rsa: ^3.6.1
  flutter_secure_storage: ^9.0.0
  hex: ^0.2.0
  crypto: ^3.0.3
  intl: ^0.18.1
  flutter_logs: ^2.1.12
  path_provider: ^2.1.3
  flutter_email_sender: ^6.0.3
  file: ^7.0.0

  # others
  oktoast: ^3.4.0

  # firebase
  firebase_core: ^2.30.1
  firebase_analytics: ^10.10.4
  firebase_crashlytics: ^3.5.4
  firebase_messaging: ^14.7.19
  flutter_local_notifications: ^17.1.2
  rxdart: ^0.27.7
  sfmc: ^8.1.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
