name: locate_us
description: "Locate Us module."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  common:
    path: "../../common"
  core:
    path: "../../core"
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.1
  flutter_svg: ^2.0.10+1
  geolocator: ^12.0.0

  go_router: ^13.0.1
  google_maps_flutter: ^2.6.1
  google_maps_flutter_android: ^2.8.0
  google_maps_flutter_platform_interface: ^2.6.0
  meta: ^1.11.0
  share_plus: ^9.0.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter: null
