name: product_details
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
# homepage:

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core
  common:
    path: ../../common
  auth:
    path: ../../features/auth
  loan:
    path: ../../features/loan
  ach:
    path: ../../shared_features/ach
  payment_gateway:
    path: ../../shared_features/payment_gateway
  appstatus:
    path: ../../features/appstatus
  product:
    path: ../../features/product    
  noc:
    path: ../../features/noc
  help:
    path: ../../shared_features/help

  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  smooth_page_indicator: ^1.1.0
  go_router: ^13.0.1
  scroll_to_index: ^3.0.1
  dartz: ^0.10.1
  intl: ^0.18.1
  time_picker_spinner: ^0.0.1
  calendar_date_picker2: ^0.5.5
  numberpicker: ^2.1.1
  badges: ^3.1.2
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.3
  pdf: ^3.10.8
  image: ^4.1.7
  image_gallery_saver: ^2.0.3
  share_plus: ^9.0.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  flutter_inappwebview: ^6.0.0
  url_launcher: ^6.2.5
  flutter_to_pdf: 0.2.0
  open_file: ^3.3.2
  scroll_to_animate_tab: ^0.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/product_details/
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
