// Mocks generated by Mockito 5.4.4 from annotations
// in ach/test/ach/presentation/cubit/ach_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i21;

import 'package:ach/data/models/create_sr_cancel_mandate_req.dart' as _i27;
import 'package:ach/data/models/create_sr_cancel_mandate_res.dart' as _i26;
import 'package:ach/data/models/create_sr_hold_mandate_req.dart' as _i29;
import 'package:ach/data/models/create_sr_hold_mandate_res.dart' as _i28;
import 'package:ach/data/models/fetch_bank_accoun_response.dart' as _i9;
import 'package:ach/data/models/fetch_bank_account_req.dart' as _i10;
import 'package:ach/data/models/generate_mandate_request.dart' as _i17;
import 'package:ach/data/models/generate_mandate_response.dart' as _i16;
import 'package:ach/data/models/generate_sr_req.dart' as _i34;
import 'package:ach/data/models/generate_sr_resp.dart' as _i33;
import 'package:ach/data/models/get_ach_loans_request.dart' as _i8;
import 'package:ach/data/models/get_ach_loans_response.dart' as _i7;
import 'package:ach/data/models/get_bank_list_resp.dart' as _i11;
import 'package:ach/data/models/get_cancel_mandate_response.dart' as _i18;
import 'package:ach/data/models/get_mandate_req.dart' as _i13;
import 'package:ach/data/models/get_mandate_res.dart' as _i12;
import 'package:ach/data/models/get_preset_uri_request.dart' as _i20;
import 'package:ach/data/models/get_preset_uri_response.dart' as _i19;
import 'package:ach/data/models/penny_drop_req.dart' as _i15;
import 'package:ach/data/models/penny_drop_resp.dart' as _i14;
import 'package:ach/data/models/reactive_mandate_req.dart' as _i31;
import 'package:ach/data/models/reactive_mandate_res.dart' as _i30;
import 'package:ach/data/models/submit_update_madate_reason_res.dart' as _i22;
import 'package:ach/data/models/submit_update_mandate_reason_req.dart' as _i23;
import 'package:ach/data/models/update_enach_request.dart' as _i25;
import 'package:ach/data/models/update_enach_response.dart' as _i24;
import 'package:ach/data/models/update_mandate_reason_resp.dart' as _i32;
import 'package:ach/data/models/validate_vpa_req.dart' as _i36;
import 'package:ach/data/models/validate_vpa_resp.dart' as _i35;
import 'package:ach/domain/repositories/ach_repository.dart' as _i2;
import 'package:ach/domain/usecases/ach_usecase.dart' as _i4;
import 'package:core/config/error/failure.dart' as _i6;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAchRepository_0 extends _i1.SmartFake implements _i2.AchRepository {
  _FakeAchRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AchUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAchUsecase extends _i1.Mock implements _i4.AchUsecase {
  MockAchUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AchRepository get achRepository => (super.noSuchMethod(
        Invocation.getter(#achRepository),
        returnValue: _FakeAchRepository_0(
          this,
          Invocation.getter(#achRepository),
        ),
      ) as _i2.AchRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.GetAchLoansResponse>>> call(
          _i8.GetAchLoansRequest? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<
                _i3.Either<_i6.Failure, List<_i7.GetAchLoansResponse>>>.value(
            _FakeEither_1<_i6.Failure, List<_i7.GetAchLoansResponse>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.GetAchLoansResponse>>>);

  @override
  _i5.Future<
      _i3.Either<_i6.Failure, _i9.FetchBankAccountResponse>> fetchBankAccount(
          _i10.FetchBankAccountRequest? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchBankAccount,
          [params],
        ),
        returnValue: _i5.Future<
                _i3.Either<_i6.Failure, _i9.FetchBankAccountResponse>>.value(
            _FakeEither_1<_i6.Failure, _i9.FetchBankAccountResponse>(
          this,
          Invocation.method(
            #fetchBankAccount,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i9.FetchBankAccountResponse>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i11.GetBankListResponse>> getBankList() =>
      (super.noSuchMethod(
        Invocation.method(
          #getBankList,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i11.GetBankListResponse>>.value(
                _FakeEither_1<_i6.Failure, _i11.GetBankListResponse>(
          this,
          Invocation.method(
            #getBankList,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i11.GetBankListResponse>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i12.GetMandateResponse>> getMandates(
          _i13.GetMandateRequest? req) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMandates,
          [req],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i12.GetMandateResponse>>.value(
                _FakeEither_1<_i6.Failure, _i12.GetMandateResponse>(
          this,
          Invocation.method(
            #getMandates,
            [req],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i12.GetMandateResponse>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i14.PennyDropResponse>> pennyDrop(
          _i15.PennyDropReq? pennyDropReq) =>
      (super.noSuchMethod(
        Invocation.method(
          #pennyDrop,
          [pennyDropReq],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i14.PennyDropResponse>>.value(
                _FakeEither_1<_i6.Failure, _i14.PennyDropResponse>(
          this,
          Invocation.method(
            #pennyDrop,
            [pennyDropReq],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i14.PennyDropResponse>>);

  @override
  _i5.Future<
      _i3.Either<_i6.Failure, _i16.GenerateMandateResponse>> generateMandateReq(
          _i17.GenerateMandateRequest? req) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateMandateReq,
          [req],
        ),
        returnValue: _i5.Future<
                _i3.Either<_i6.Failure, _i16.GenerateMandateResponse>>.value(
            _FakeEither_1<_i6.Failure, _i16.GenerateMandateResponse>(
          this,
          Invocation.method(
            #generateMandateReq,
            [req],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i16.GenerateMandateResponse>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i18.GetCancelMandateReasonResponse>>>
      getCancelMandateReason() => (super.noSuchMethod(
            Invocation.method(
              #getCancelMandateReason,
              [],
            ),
            returnValue: _i5.Future<
                    _i3.Either<_i6.Failure,
                        List<_i18.GetCancelMandateReasonResponse>>>.value(
                _FakeEither_1<_i6.Failure,
                    List<_i18.GetCancelMandateReasonResponse>>(
              this,
              Invocation.method(
                #getCancelMandateReason,
                [],
              ),
            )),
          ) as _i5.Future<
              _i3
              .Either<_i6.Failure, List<_i18.GetCancelMandateReasonResponse>>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i19.GetPresetUriResponse>> getPresetUri(
          _i20.GetPresetUriRequest? req) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPresetUri,
          [req],
        ),
        returnValue: _i5
            .Future<_i3.Either<_i6.Failure, _i19.GetPresetUriResponse>>.value(
            _FakeEither_1<_i6.Failure, _i19.GetPresetUriResponse>(
          this,
          Invocation.method(
            #getPresetUri,
            [req],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i19.GetPresetUriResponse>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> uploadDocument(
    String? presetUrl,
    _i21.File? file,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadDocument,
          [
            presetUrl,
            file,
          ],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
            _FakeEither_1<_i6.Failure, String>(
          this,
          Invocation.method(
            #uploadDocument,
            [
              presetUrl,
              file,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, String>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> deleteDocument(
          String? presetUrl) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDocument,
          [presetUrl],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
            _FakeEither_1<_i6.Failure, String>(
          this,
          Invocation.method(
            #deleteDocument,
            [presetUrl],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, String>>);


  _i5.Future<_i3.Either<_i6.Failure, _i22.SubmitUpdateMandateResponse>>
      submitUpdateMandateReason(_i23.SubmitUpdateMandateReasonReq? req) =>
          (super.noSuchMethod(
            Invocation.method(
              #submitUpdateMandateReason,
              [req],
            ),
            returnValue: _i5.Future<
                    _i3.Either<_i6.Failure,
                        _i22.SubmitUpdateMandateResponse>>.value(
                _FakeEither_1<_i6.Failure, _i22.SubmitUpdateMandateResponse>(
              this,
              Invocation.method(
                #submitUpdateMandateReason,
                [req],
              ),
            )),
          ) as _i5.Future<
              _i3.Either<_i6.Failure, _i22.SubmitUpdateMandateResponse>>);


  _i5.Future<
      _i3.Either<_i6.Failure, _i24.UpdateEnachStatusResponse>> updateEnach(
          _i25.UpdateEnachStatusRequest? req) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEnach,
          [req],
        ),
        returnValue: _i5.Future<
                _i3.Either<_i6.Failure, _i24.UpdateEnachStatusResponse>>.value(
            _FakeEither_1<_i6.Failure, _i24.UpdateEnachStatusResponse>(
          this,
          Invocation.method(
            #updateEnach,
            [req],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i24.UpdateEnachStatusResponse>>);


  _i5.Future<_i3.Either<_i6.Failure, _i26.CreateSrCancelMandateRes>>
      createSRCancelMandate(_i27.CreateSrCancelMandateReq? req) =>
          (super.noSuchMethod(
            Invocation.method(
              #createSRCancelMandate,
              [req],
            ),
            returnValue: _i5.Future<
                    _i3
                    .Either<_i6.Failure, _i26.CreateSrCancelMandateRes>>.value(
                _FakeEither_1<_i6.Failure, _i26.CreateSrCancelMandateRes>(
              this,
              Invocation.method(
                #createSRCancelMandate,
                [req],
              ),
            )),
          ) as _i5
              .Future<_i3.Either<_i6.Failure, _i26.CreateSrCancelMandateRes>>);


  _i5.Future<
      _i3.Either<_i6.Failure, _i28.CreateSrHoldMandateRes>> createSRHoldMandate(
          _i29.CreateSrHoldMandateReq? req) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSRHoldMandate,
          [req],
        ),
        returnValue: _i5
            .Future<_i3.Either<_i6.Failure, _i28.CreateSrHoldMandateRes>>.value(
            _FakeEither_1<_i6.Failure, _i28.CreateSrHoldMandateRes>(
          this,
          Invocation.method(
            #createSRHoldMandate,
            [req],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i28.CreateSrHoldMandateRes>>);


  _i5.Future<_i3.Either<_i6.Failure, _i30.ReactiveMandateRes>> reactiveMandate(
          _i31.ReactiveMandateReq? req) =>
      (super.noSuchMethod(
        Invocation.method(
          #reactiveMandate,
          [req],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i30.ReactiveMandateRes>>.value(
                _FakeEither_1<_i6.Failure, _i30.ReactiveMandateRes>(
          this,
          Invocation.method(
            #reactiveMandate,
            [req],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i30.ReactiveMandateRes>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i32.UpdateMandateReasonResp>>>
      getUpdateMandateReason() => (super.noSuchMethod(
            Invocation.method(
              #getUpdateMandateReason,
              [],
            ),
            returnValue: _i5.Future<
                    _i3.Either<_i6.Failure,
                        List<_i32.UpdateMandateReasonResp>>>.value(
                _FakeEither_1<_i6.Failure, List<_i32.UpdateMandateReasonResp>>(
              this,
              Invocation.method(
                #getUpdateMandateReason,
                [],
              ),
            )),
          ) as _i5.Future<
              _i3.Either<_i6.Failure, List<_i32.UpdateMandateReasonResp>>>);


  _i5.Future<_i3.Either<_i6.Failure, _i33.GenerateSrResponse>> generateSR(
          _i34.GenerateSrRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateSR,
          [request],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i33.GenerateSrResponse>>.value(
                _FakeEither_1<_i6.Failure, _i33.GenerateSrResponse>(
          this,
          Invocation.method(
            #generateSR,
            [request],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i33.GenerateSrResponse>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i35.ValidateVpaResp>> validateVpa(
          _i36.ValidateVpaReq? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateVpa,
          [request],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i35.ValidateVpaResp>>.value(
                _FakeEither_1<_i6.Failure, _i35.ValidateVpaResp>(
          this,
          Invocation.method(
            #validateVpa,
            [request],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i35.ValidateVpaResp>>);
}
