const Map<String, bool> featureFlagDev = {
  "loan.fore_closure": true,
  "loan.cancellation": true,
  "loan.ach_mandate": true,
  "product.app_status": true,
  "product.lead_gen": true,
  "product.product_features": true,
  "loan.payment": true,
  "enable_jailbreak": false,
  "enable_stubdata": false,
  "browser_stack": true,
  "product.faq": true,
  "auth.enable_customlogin": false,
  "app.enable_logs": true,
  "service.loan.details":true,
  "service.documents":true,
  "service.noc":true,
  "service.bureau":true,
  "service.refund":true,
  "service.rcupdate":true,
  "service.profile":true,
  "product.product_details": true,
  "service.payment&charges":true,
};
