// Mocks generated by Mockito 5.4.4 from annotations
// in product/test/lib/presentation/cubit/product_feature_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:core/config/error/failure.dart' as _i6;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:product/data/models/product_feature_request.dart' as _i8;
import 'package:product/data/models/product_feature_response.dart' as _i7;
import 'package:product/domain/repositories/product_feature_repository.dart'
    as _i2;
import 'package:product/domain/usecases/product_feature_usecase.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductFeatureRepository_0 extends _i1.SmartFake
    implements _i2.ProductFeatureRepository {
  _FakeProductFeatureRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductFeatureUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductFeatureUseCase extends _i1.Mock
    implements _i4.ProductFeatureUseCase {
  MockProductFeatureUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductFeatureRepository get productFeatureRepository =>
      (super.noSuchMethod(
        Invocation.getter(#productFeatureRepository),
        returnValue: _FakeProductFeatureRepository_0(
          this,
          Invocation.getter(#productFeatureRepository),
        ),
      ) as _i2.ProductFeatureRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.ProductFeatureResponse>> call(
          _i8.ProductFeatureRequest? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5
            .Future<_i3.Either<_i6.Failure, _i7.ProductFeatureResponse>>.value(
            _FakeEither_1<_i6.Failure, _i7.ProductFeatureResponse>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.ProductFeatureResponse>>);
}

/// A class which mocks [Failure].
///
/// See the documentation for Mockito's code generation for more information.
class MockFailure extends _i1.Mock implements _i6.Failure {
  MockFailure() {
    _i1.throwOnMissingStub(this);
  }
}
